"""Create table

Revision ID: 82313539df5c
Revises: 
Create Date: 2023-10-21 23:26:16.352202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82313539df5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
